// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CustomField struct {
	FieldID      string  `json:"FieldID"`
	FieldName    string  `json:"FieldName"`
	DataType     string  `json:"DataType"`
	Value        string  `json:"Value"`
	MaxValue     int     `json:"MaxValue"`
	MinValue     int     `json:"MinValue"`
	DefaultValue *string `json:"DefaultValue"`
	IsRequired   bool    `json:"IsRequired"`
	Visibility   bool    `json:"Visibility"`
}

type NewCustomField struct {
	FieldName    string  `json:"FieldName"`
	DataType     string  `json:"DataType"`
	Value        string  `json:"Value"`
	MaxValue     int     `json:"MaxValue"`
	MinValue     int     `json:"MinValue"`
	DefaultValue *string `json:"DefaultValue"`
	IsRequired   *bool   `json:"IsRequired"`
	Visibility   *bool   `json:"Visibility"`
}

type NewTable struct {
	Fields []*NewCustomField `json:"Fields"`
}

type Table struct {
	TableID string         `json:"TableID"`
	Fields  []*CustomField `json:"Fields"`
}
